name: homo_habitus
description: Discover yourself through habits

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  bloc: ^7.1.0
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  rxdart: ^0.27.2
  table_calendar: ^3.0.2
  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  moor_generator: ^4.5.1
  build_runner: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/icons/